export enum CoffeeFlavorEnum {
    COFFEE_FLAVOR_VANILLA = 'COFFEE_FLAVOR_VANILLA',
    COFFEE_FLAVOR_CARAMEL = 'COFFEE_FLAVOR_CARAMEL',
    COFFEE_FLAVOR_PSL = 'COFFEE_FLAVOR_PSL',
    COFFEE_FLAVOR_MOCHA = 'COFFEE_FLAVOR_MOCHA',
    COFFEE_FLAVOR_HAZELNUT = 'COFFEE_FLAVOR_HAZELNUT',
}